[project]
name = "datafest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython==8.26.0",
    "jupyterlab==4.5.0",
    "matplotlib==3.9.0",
    "mlxtend==0.23.1",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "plotly==5.22.0",
    "polars>=1.38.1",
    "pywaffle==1.1.1",
    "scikit-learn==1.5.0",
    "scipy==1.14.0",
    "seaborn==0.13.2",
    "squarify==0.4.3",
    "uvicorn>=0.41.0",
    "fastapi>=0.100.0",
    "xlsxwriter>=3.2.9",
    "lightgbm>=4.6.0",
    "shap>=0.49.1",
    "pyarrow>=23.0.1",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "polars>=1.38.1",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "bs4>=0.0.2",
]
